# EOL Test Configuration
# Hardware pins are loaded from hardware_config.yaml

# Whether or not to use the TofuPilot operator UI and result collection interface
use_tofupilot: False

# Set procedure ID and part_number to match what's in TofuPilot (create a procedure ahead of time)
procedure_id: e7ba6f6c-8ec9-11f0-aec1-f39e79a20a3c
part_number: LURA_M2

# EOL Test thresholds
thresholds:
  # Smoke test thresholds
  vbat_voltage_min: 2.60
  vbat_voltage_max: 2.66
  vbat_current_max: 10.0e-6  # 10uA
  
  vsys_voltage_min: 2.60
  vsys_voltage_max: 2.66
  vsys_current_max: 5.0e-3   # 5mA
  
  # UART test thresholds
  uart_uptime_max: 3000.0       # ms
  
  # Magnetic latch test thresholds
  mag_latch_current_max: 10.0e-6  # 10uA
  
  # ISFET test thresholds
  isfet_vout_min: 0.0
  isfet_vout_max: 2.63
  isfet_vout_max_delta: 0.75      # Max difference between Joulescope and DUT measurement of ISFET_VOUT
  isfet_id_current_min: 95.0e-6   # 95uA (100uA - 5%)
  isfet_id_current_max: 105.0e-6  # 105uA (100uA + 5%)
  isfet_vds_voltage_min: 0.57     # 570mV (600mV - 5%)
  isfet_vds_voltage_max: 0.63     # 630mV (600mV + 5%)
  
  # BLE test thresholds
  ble_vd_min: 0.6175         # 617.5mV (650mV - 5%)
  ble_vd_max: 0.6825         # 682.5mV (650mV + 5%)
  ble_vs_min: 0.0475         # 47.5mV (50mV - 5%)
  ble_vs_max: 0.0525         # 52.5mV (50mV + 5%)
  ble_vbat_min: 2.60         # 2.60V (2.63V - 1%)
  ble_vbat_max: 2.66         # 2.66V (2.63V + 1%)

  # RF Power thresholds
  rf_power_min: 0     # dBm
  rf_power_max: 100   # dBm

  # Coil impedence thresholds
  coil_rx_impedance_min: 0    # Ohm
  coil_rx_impedance_max: 100  # Ohm

ble_sensor_data_service_uuid: eb916eba-dd6b-4ec7-b25c-62d69992c410
sense_enable_characteristic_uuid: 270c46d0-0382-4732-a35b-491ed5fb1318

# This measurement array is dynamic, each entry will be validatated against a BLE measurement of that characteristic.
# The min/max are scaled values. BLE data is read as a 16-bit Little-endian integer, divided by scale and then compared to min/max.
# In other words: value = raw / scale and the check is: min < value < max
ble_measurements:
  - uuid: 611bf18b-0e2b-451d-ad71-ca02419e0d28
    name: ph
    min: 0
    max: 10.0
    scale: 1000 # mV to V
  - uuid: 43d2b9e3-7a5f-4a04-b864-b4687ca505c8
    name: temperature
    min: 0
    max: 100
    scale: 1000 # mV to V
  - uuid: d35c35aa-91a8-4f6d-a8c2-ec2860cb95bf
    name: battery_voltage
    min: 0
    max: 3.3
    scale: 1000 # mV to V
